import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TRQuery from "@/components/provider/ReactQuery";
import Navbar from "@/components/Layouts/Navbar ";

const inter = Inter( { subsets: [ "latin" ] } );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en" data-theme='cupcake'>
      <body className={ inter.className }>
        <TRQuery>
          {/* <div className="bg-red-200 p-2"> */}

            <div className="min-h-screen  bg-red-200 pt-24">
            <Navbar />
              { children }
            {/* </div> */}
          </div>
        </TRQuery>
      </body>
    </html>
  );
}
