import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import TRQuery from "@/components/provider/ReactQuery";
import NextAuthProvider from "@/components/provider/NextAuthProvider";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import React from "react";
import LayoutNext from "@/components/provider/LayoutNext";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme='cupcake'>
    <body className={inter.className}>
    <NextAuthProvider>
      <TRQuery>
        <LayoutNext>
          {children}
        </LayoutNext>
        <ToastContainer/>
      </TRQuery>
    </NextAuthProvider>
    </body>
    </html>
  );
}
