/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vTUsfYBNwu7
 */
import Link from "next/link"

export function PageNotFound() {
  return (
    <div className="flex items-center justify-center w-full min-h-[80vh] px-4 text-center md:px-6">
      <div className="space-y-4">
        <div className="inline-flex rounded-lg border border-gray-200 bg-white px-3 py-1 text-sm shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
          404
        </div>
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Page Not Found</h1>
          <p className="max-w-[600px] mx-auto text-gray-500 md:text-xl/relaxed dark:text-gray-400">
            We can't seem to find the page you're looking for.
          </p>
        </div>
        <div>
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
            href="#"
          >
            Go Back
          </Link>
        </div>
      </div>
    </div>
  )
}
