/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ibvcWKHe9jA
 */
import Link from "next/link"

export function Unauthorized() {
  return (
    <div className="flex flex-col h-screen p-4 items-center justify-center gap-4 text-center">
      <div className="w-full max-w-[400px]">
        <div className="space-y-2">
          <h1 className="text-4xl font-extrabold tracking-tighter">Unauthorized</h1>
          <p className="text-gray-500 dark:text-gray-400">You do not have permission to access this resource.</p>
        </div>
        <Link
          className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900     "
          href="#"
        >
          Go Back
        </Link>
      </div>
    </div>
  )
}
